# fly.toml app configuration file generated for chassiro-api on 2026-04-30T17:12:34-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'chassiro-api'
primary_region = 'gru'

[build]
  dockerfile = 'Dockerfile'

[env]
  CHASSI_SNAPSHOT_PATH = '/app/chassi.json'
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/health'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
  cpus = 1
  memory_mb = 256
